# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 09:05
from __future__ import unicode_literals

import core.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created', core.fields.AutoCreatedField(default=core.fields.now_without_millisecs, editable=False)),
                ('modified', core.fields.AutoLastModifiedField(default=core.fields.now_without_millisecs, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('address_line1', models.CharField(blank=True, max_length=500)),
                ('address_line2', models.CharField(blank=True, max_length=500)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('locality', models.CharField(blank=True, max_length=100)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('company_type', models.CharField(choices=[('plc', 'Public limited company'), ('icvc-warrant', 'Investment company with variable capital'), ('limited-partnership', 'Limited partnership'), ('royal-charter', 'Royal charter company'), ('other', 'Other company type'), ('private-unlimited', 'Private unlimited company'), ('private-limited-guarant-nsc', 'Private limited by guarantee without share capital'), ('old-public-company', 'Old public company'), ('eeig', 'European economic interest grouping (EEIG)'), ('converted-or-closed', 'Converted / closed'), ('industrial-and-provident-society', 'Industrial and provident society'), ('northern-ireland', 'Northern Ireland company'), ('european-public-limited-liability-company-se', 'European public limited liability company (SE)'), ('private-limited-guarant-nsc-limited-exemption', 'Private Limited Company by guarantee without share capital, use of &#39;Limited&#39; exemption'), ('private-unlimited-nsc', 'Private unlimited company without share capital'), ('uk-establishment', 'UK establishment company'), ('icvc-securities', 'Investment company with variable capital'), ('northern-ireland-other', 'Credit union (Northern Ireland)'), ('llp', 'Limited liability partnership'), ('unregistered-company', 'Unregistered company'), ('icvc-umbrella', 'Investment company with variable capital'), ('assurance-company', 'Assurance company'), ('investment-company-with-variable-capital', 'Investment company with variable capital'), ('oversea-company', 'Overseas company'), ('ltd', 'Private limited company'), ('private-limited-shares-section-30-exemption', 'Private Limited Company, use of &#39;Limited&#39; exemption')], max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('insolvency-proceedings', 'Insolvency Proceedings'), ('active', 'Active'), ('open', 'Open'), ('voluntary-arrangement', 'Voluntary Arrangement'), ('receivership', 'Receivership'), ('closed', 'Closed'), ('administration', 'In Administration'), ('dissolved', 'Dissolved'), ('converted-closed', 'Converted / Closed'), ('liquidation', 'Liquidation')], max_length=150)),
                ('date_of_creation', models.DateField(null=True)),
                ('date_of_dissolution', models.DateField(null=True)),
                ('raw', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyPreviousName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', core.fields.AutoCreatedField(default=core.fields.now_without_millisecs, editable=False)),
                ('modified', core.fields.AutoLastModifiedField(default=core.fields.now_without_millisecs, editable=False)),
                ('change_date', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companieshouse.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanySicCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', core.fields.AutoCreatedField(default=core.fields.now_without_millisecs, editable=False)),
                ('modified', core.fields.AutoLastModifiedField(default=core.fields.now_without_millisecs, editable=False)),
                ('code', models.CharField(max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companieshouse.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
