# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-03 15:02
from __future__ import unicode_literals

from django.db import connection
from django.db import migrations


def create_pg_trgm_extension(apps, schema_editor):
    cursor = connection.cursor()
    cursor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")


class Migration(migrations.Migration):

    dependencies = [
        ('companieshouse', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_pg_trgm_extension),
    ]
