# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-03 15:05
from __future__ import unicode_literals

from django.db import connection
from django.db import migrations


INDEX_NAME = 'ch_company_name_trgm_idx'


def create_index_extension(apps, schema_editor):
    cursor = connection.cursor()
    cursor.execute("SELECT to_regclass('{}')".format(INDEX_NAME))

    if not cursor.fetchall():
        cursor.execute(
            "CREATE INDEX {} ON companieshouse_company USING GIN (name gin_trgm_ops)".format(INDEX_NAME)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('companieshouse', '0002_auto_20160603_1502'),
    ]

    operations = [
        migrations.RunPython(create_index_extension),
    ]
