# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 09:21
from __future__ import unicode_literals

import core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', core.fields.AutoCreatedField(default=core.fields.now_without_millisecs, editable=False)),
                ('modified', core.fields.AutoLastModifiedField(default=core.fields.now_without_millisecs, editable=False)),
                ('cdms_pk', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', core.fields.AutoCreatedField(default=core.fields.now_without_millisecs, editable=False)),
                ('modified', core.fields.AutoLastModifiedField(default=core.fields.now_without_millisecs, editable=False)),
                ('cdms_pk', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, max_length=255)),
                ('uk_organisation', models.BooleanField(default=True)),
                ('country', models.CharField(choices=[('80756b9a-5d95-e211-a939-e4115bead28a', 'United Kingdom')], max_length=255)),
                ('postcode', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('uk_region', models.CharField(blank=True, choices=[('874cd12a-6095-e211-a939-e4115bead28a', 'London')], max_length=255)),
                ('country_code', models.CharField(max_length=255)),
                ('area_code', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
                ('sector', models.CharField(choices=[('a538cecc-5f95-e211-a939-e4115bead28a', 'Food & Drink')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='organisation',
            field=core.fields.UKTIForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.Organisation'),
        ),
    ]
