# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0005_auto_20160512_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='account_number',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address1_address_cdms_pk',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address1_city',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address1_country',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address1_county',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address1_fax',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address1_freight_terms_code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address1_line1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address1_line2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address1_line3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address1_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address1_post_office_box',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address1_postal_code',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address1_primary_contact_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address1_state_or_province',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address1_telephone1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address1_telephone2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address1_telephone3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address1_ups_zone',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address2_address_cdms_pk',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address2_city',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address2_country',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address2_county',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address2_fax',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address2_freight_terms_code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address2_line1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address2_line2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address2_line3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address2_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address2_post_office_box',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address2_postal_code',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address2_primary_contact_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address2_state_or_province',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address2_telephone1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address2_telephone2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address2_telephone3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address2_ups_zone',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address4',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address_comment',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='area_code',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='balance_sheet',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='balance_sheet_year',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='city',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='companies_house_status',
            field=models.CharField(blank=True, choices=[('db65bea3-ad99-e511-88b6-e4115bead28a', 'Ceased Trading'), ('69756b9a-5d95-e211-a939-e4115bead28a', 'Dissolved'), ('6a756b9a-5d95-e211-a939-e4115bead28a', 'Liquidation'), ('6b756b9a-5d95-e211-a939-e4115bead28a', 'Receivership')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='complete_address',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='country_code',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='created_by',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='created_on_behalf_by',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='database_source',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='default_price_level_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='email_address1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='email_address2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='email_address3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='extension',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='extra_address_ref',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='extra_email_ref',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='extra_telephone_ref',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='fax',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='ftp_site_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='full_telephone_number',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='industry_code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='linkedin',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='local_language_address',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='local_language_postcode',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='master_cdms_pk',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='modified_by',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='modified_on_behalf_by',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='og_address_id',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='og_created_by',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='og_email_address_id',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='og_modified_by',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='og_organization_id',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='og_telephone_id',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_sector_ref',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_size_year',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='originating_lead_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='owner_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='ownership_code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='owning_team',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='owning_user',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='parent_cdms_pk',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='payment_terms_code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='preferred_appointment_day_code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='preferred_appointment_time_code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='preferred_contact_method_code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='preferred_equipment_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='preferred_service_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='preferred_system_user_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='primary_contact_cdms_pk',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='reference_code',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='sic',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='state_county',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='stock_exchange',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='telephone1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='telephone2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='telephone3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='temp_address',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='territory_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='ticker_symbol',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='townCity',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='twitter',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='ukti_registration_number',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='vat_number',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='website_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='yomi_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
