# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 14:30
from __future__ import unicode_literals

import core.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0009_organisation_verified_companies_house_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHOrganisation',
            fields=[
                ('created', core.fields.AutoCreatedField(default=core.fields.now_without_millisecs, editable=False)),
                ('modified', core.fields.AutoLastModifiedField(default=core.fields.now_without_millisecs, editable=False)),
                ('number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=10)),
                ('raw', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='verified_companies_house_number',
        ),
        migrations.AddField(
            model_name='organisation',
            name='verified_ch_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisation.CHOrganisation'),
        ),
    ]
