# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0010_auto_20160518_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
