# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0011_organisation_last_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chorganisation',
            name='source',
            field=models.CharField(choices=[('CH', 'Companies House'), ('DUEDIL', 'DueDil')], max_length=10),
        ),
    ]
