from cdms_api import fields as cdms_fields

from migrator.cdms_migrator import BaseCDMSMigrator


class OrganisationMigrator(BaseCDMSMigrator):
    fields = {
        'address1': cdms_fields.StringField('optevia_Address1'),
        'address1_name': cdms_fields.StringField('Address1_Name'),
        'address1_line1': cdms_fields.StringField('Address1_Line1'),
        'address1_line2': cdms_fields.StringField('Address1_Line2'),
        'address1_line3': cdms_fields.StringField('Address1_Line3'),
        'address1_county': cdms_fields.StringField('Address1_County'),
        'address1_postal_code': cdms_fields.StringField('Address2_PostalCode'),
        'address1_city': cdms_fields.StringField('Address1_City'),
        'address1_state_or_province': cdms_fields.StringField('Address1_StateOrProvince'),
        'address1_country': cdms_fields.StringField('Address1_Country'),
        'address1_post_office_box': cdms_fields.StringField('Address1_PostOfficeBox'),
        'address1_fax': cdms_fields.StringField('Address1_Fax'),
        'address1_telephone1': cdms_fields.StringField('Address1_Telephone1'),
        'address1_telephone2': cdms_fields.StringField('Address1_Telephone2'),
        'address1_telephone3': cdms_fields.StringField('Address1_Telephone3'),
        'address1_primary_contact_name': cdms_fields.StringField('Address1_PrimaryContactName'),
        'address1_ups_zone': cdms_fields.StringField('Address1_UPSZone'),
        'address1_utc_offset': cdms_fields.IntegerField('Address1_UTCOffset'),
        'address1_freight_terms_code': cdms_fields.OptionSetValueField('Address1_FreightTermsCode'),
        'address1_shipping_method_code': cdms_fields.OptionSetValueField('Address1_ShippingMethodCode'),
        'address1_address_type_code': cdms_fields.OptionSetValueField('Address1_AddressTypeCode'),
        'address1_latitude': cdms_fields.DecimalField('Address1_Latitude'),
        'address1_longitude': cdms_fields.DecimalField('Address1_Longitude'),
        'address1_address_cdms_pk': cdms_fields.StringField('Address1_AddressId'),

        'address2': cdms_fields.StringField('optevia_Address2'),
        'address2_name': cdms_fields.StringField('Address2_Name'),
        'address2_line1': cdms_fields.StringField('Address2_Line1'),
        'address2_line2': cdms_fields.StringField('Address2_Line2'),
        'address2_line3': cdms_fields.StringField('Address2_Line3'),
        'address2_county': cdms_fields.StringField('Address2_County'),
        'address2_postal_code': cdms_fields.StringField('Address2_PostalCode'),
        'address2_city': cdms_fields.StringField('Address2_City'),
        'address2_state_or_province': cdms_fields.StringField('Address2_StateOrProvince'),
        'address2_country': cdms_fields.StringField('Address2_Country'),
        'address2_post_office_box': cdms_fields.StringField('Address2_PostOfficeBox'),
        'address2_fax': cdms_fields.StringField('Address2_Fax'),
        'address2_telephone1': cdms_fields.StringField('Address2_Telephone1'),
        'address2_telephone2': cdms_fields.StringField('Address2_Telephone2'),
        'address2_telephone3': cdms_fields.StringField('Address2_Telephone3'),
        'address2_primary_contact_name': cdms_fields.StringField('Address2_PrimaryContactName'),
        'address2_ups_zone': cdms_fields.StringField('Address2_UPSZone'),
        'address2_utc_offset': cdms_fields.IntegerField('Address2_UTCOffset'),
        'address2_freight_terms_code': cdms_fields.OptionSetValueField('Address2_FreightTermsCode'),
        'address2_shipping_method_code': cdms_fields.OptionSetValueField('Address2_ShippingMethodCode'),
        'address2_address_type_code': cdms_fields.OptionSetValueField('Address2_AddressTypeCode'),
        'address2_latitude': cdms_fields.DecimalField('Address2_Latitude'),
        'address2_longitude': cdms_fields.DecimalField('Address2_Longitude'),
        'address2_address_cdms_pk': cdms_fields.StringField('Address2_AddressId'),

        'address3': cdms_fields.StringField('optevia_Address3'),

        'telephone2': cdms_fields.StringField('Telephone2'),
        'telephone3': cdms_fields.StringField('Telephone3'),
        'city': cdms_fields.StringField('optevia_TownCity'),

        'territory_code': cdms_fields.OptionSetValueField('TerritoryCode'),
        'companies_house_status': cdms_fields.IdRefField('optevia_CompaniesHouseStatus'),
        'last_used_in_campaign': cdms_fields.DateTimeField('LastUsedInCampaign'),
        'timezone_rule_version_number': cdms_fields.IntegerField('TimeZoneRuleVersionNumber'),
        'overridden_created_on': cdms_fields.DateTimeField('OverriddenCreatedOn'),
        'vat_number': cdms_fields.StringField('optevia_VATNumber'),
        'ownership_code': cdms_fields.OptionSetValueField('OwnershipCode'),
        'customer_size_code': cdms_fields.OptionSetValueField('CustomerSizeCode'),
        'og_telephone_id': cdms_fields.StringField('optevia_OG_TELEPHONE_ID'),
        'product_description': cdms_fields.StringField('optevia_ProductDescription'),
        'balance_sheet': cdms_fields.StringField('optevia_BalanceSheet'),
        'version_number': cdms_fields.IntegerField('VersionNumber'),
        'opt_number_of_employees': cdms_fields.DecimalField('optevia_NumberofEmployees'),
        'revision': cdms_fields.DecimalField('optevia_Revision'),
        'do_not_bulk_postal_mail': cdms_fields.BooleanField('DoNotBulkPostalMail'),
        'og_modified': cdms_fields.DateTimeField('optevia_OG_MODIFIED'),
        'local_language_postcode': cdms_fields.StringField('optevia_LocalLanguagePostCode'),
        'do_not_postal_mail': cdms_fields.BooleanField('DoNotPostalMail'),
        'og_created_by': cdms_fields.StringField('optevia_OG_CREATED_BY'),
        'extension': cdms_fields.StringField('optevia_Extension'),
        'address_comment': cdms_fields.StringField('optevia_AddressComment'),
        'merged': cdms_fields.StringField('Merged'),
        'twitter': cdms_fields.StringField('optevia_Twitter'),
        'parent_owned': cdms_fields.DecimalField('optevia_ParentOwned'),
        'og_organization_id': cdms_fields.StringField('optevia_OG_ORGANIZATION_ID'),
        'do_not_bulk_email': cdms_fields.BooleanField('DoNotBulkEMail'),
        'email_address3': cdms_fields.StringField('EMailAddress3'),
        'website_url': cdms_fields.StringField('WebSiteURL'),
        'linkedin': cdms_fields.StringField('optevia_LinkedIn'),
        'description': cdms_fields.StringField('Description'),
        'companies_house_number': cdms_fields.StringField('optevia_CompaniesHouseNumber'),
        'ticker_symbol': cdms_fields.StringField('TickerSymbol'),
        'sector': cdms_fields.IdRefField('optevia_Sector'),
        'sic': cdms_fields.StringField('SIC'),
        'local_language_address': cdms_fields.StringField('optevia_LocalLanguageAddress'),
        'og_address_id': cdms_fields.StringField('optevia_OG_ADDRESS_ID'),
        'ukti_registration_number': cdms_fields.StringField('optevia_UKTIRegistrationNumber'),
        'organisation_size_year': cdms_fields.StringField('optevia_OrganisationSizeYear'),
        'temp_address': cdms_fields.StringField('optevia_TempAddress'),
        'do_not_fax': cdms_fields.BooleanField('DoNotFax'),
        'alias': cdms_fields.StringField('optevia_Alias'),
        'extra_telephone_ref': cdms_fields.StringField('optevia_ExtraTelephoneRef'),
        'utc_conversion_timezone_code': cdms_fields.IntegerField('UTCConversionTimeZoneCode'),
        'number_of_employees': cdms_fields.IntegerField('NumberOfEmployees'),
        'do_not_email': cdms_fields.BooleanField('DoNotEMail'),
        'address4': cdms_fields.StringField('optevia_Address4'),
        'extra_address_ref': cdms_fields.StringField('optevia_ExtraAddressRef'),
        'telephone1': cdms_fields.StringField('Telephone1'),
        'yomi_name': cdms_fields.StringField('YomiName'),
        'last_verified': cdms_fields.DateTimeField('optevia_LastVerified'),
        'concatenated_address': cdms_fields.StringField('optevia_ConcatenatedAddress'),
        'do_not_send_mm': cdms_fields.BooleanField('DoNotSendMM'),
        'fax': cdms_fields.StringField('Fax'),
        'balance_sheet_year': cdms_fields.StringField('optevia_BalanceSheetYear'),
        'participates_in_workflow': cdms_fields.BooleanField('ParticipatesInWorkflow'),
        'reference_code': cdms_fields.StringField('optevia_ReferenceCode'),
        'comments': cdms_fields.StringField('optevia_Comments'),
        'full_telephone_number': cdms_fields.StringField('optevia_FullTelephoneNumber'),
        'organisation_sector_ref': cdms_fields.StringField('optevia_organisationsectorref'),
        'credit_on_hold': cdms_fields.BooleanField('CreditOnHold'),
        'created_on': cdms_fields.DateTimeField('CreatedOn'),
        'name': cdms_fields.StringField('Name'),
        'source_obsolete': cdms_fields.IntegerField('optevia_SourceObsolete'),
        'area_code': cdms_fields.StringField('optevia_AreaCode'),
        'og_email_address_id': cdms_fields.StringField('optevia_OG_EMAILADDRESS_ID'),
        'country_code': cdms_fields.StringField('optevia_CountryCode'),
        'extra_email_ref': cdms_fields.StringField('optevia_ExtraEmailRef'),
        'account_number': cdms_fields.StringField('AccountNumber'),
        'ftp_site_url': cdms_fields.StringField('FtpSiteURL'),
        'stopflag': cdms_fields.BooleanField('detica_stopflag'),
        'do_not_phone': cdms_fields.BooleanField('DoNotPhone'),
        'uk_organisation': cdms_fields.BooleanField('optevia_ukorganisation'),
        'og_modified_by': cdms_fields.StringField('optevia_OG_MODIFIED_BY'),
        'postcode': cdms_fields.StringField('optevia_PostCode'),
        'stock_exchange': cdms_fields.StringField('StockExchange'),
        'state_county': cdms_fields.StringField('optevia_StateCounty'),
        'og_created': cdms_fields.DateTimeField('optevia_OG_CREATED'),
        'local_name': cdms_fields.StringField('optevia_LocalName'),
        'shares_outstanding': cdms_fields.IntegerField('SharesOutstanding'),
        'paf_override': cdms_fields.BooleanField('optevia_PAFOverride'),
        'modified_on': cdms_fields.DateTimeField('ModifiedOn'),
        'telephone_number': cdms_fields.StringField('optevia_TelephoneNumber'),
        'email_address1': cdms_fields.StringField('EMailAddress1'),
        'import_sequence_number': cdms_fields.IntegerField('ImportSequenceNumber'),
        'complete_address': cdms_fields.StringField('optevia_CompleteAddress'),
        'exchange_rate': cdms_fields.DecimalField('ExchangeRate'),

        'credit_limit': cdms_fields.OptionSetValueField('CreditLimit'),
        'credit_limit_base': cdms_fields.OptionSetValueField('CreditLimit_Base'),
        'aging_90': cdms_fields.OptionSetValueField('Aging90'),
        'aging_90_base': cdms_fields.OptionSetValueField('Aging90_Base'),
        'aging_60': cdms_fields.OptionSetValueField('Aging60'),
        'aging_60_base': cdms_fields.OptionSetValueField('Aging60_Base'),
        'aging_30': cdms_fields.OptionSetValueField('Aging30'),
        'aging_30_base': cdms_fields.OptionSetValueField('Aging30_Base'),
        'revenue': cdms_fields.OptionSetValueField('Revenue'),
        'revenue_base': cdms_fields.OptionSetValueField('Revenue_Base'),
        'market_cap': cdms_fields.OptionSetValueField('MarketCap'),
        'market_cap_base': cdms_fields.OptionSetValueField('MarketCap_Base'),
        'turnover': cdms_fields.OptionSetValueField('optevia_Turnover'),
        'turnover_base': cdms_fields.OptionSetValueField('optevia_turnover_Base'),


        'investment_experience': cdms_fields.IdRefField('optevia_InvestmentExperience'),
        'export_experience': cdms_fields.IdRefField('optevia_ExportExperience'),

        'owning_business_unit': cdms_fields.IdRefField('OwningBusinessUnit'),
        'location_type': cdms_fields.IdRefField('optevia_LocationType'),

        'shipping_method_code': cdms_fields.OptionSetValueField('ShippingMethodCode'),

        'preferred_appointment_day_code': cdms_fields.OptionSetValueField('PreferredAppointmentDayCode'),
        'payment_terms_code': cdms_fields.OptionSetValueField('PaymentTermsCode'),
        'status_code': cdms_fields.OptionSetValueField('StatusCode'),
        'industry_code': cdms_fields.OptionSetValueField('IndustryCode'),
        'preferred_appointment_time_code': cdms_fields.OptionSetValueField('PreferredAppointmentTimeCode'),
        'preferred_contact_method_code': cdms_fields.OptionSetValueField('PreferredContactMethodCode'),

        'country': cdms_fields.IdRefField('optevia_Country'),

        'sector_nature_of_interest': cdms_fields.IdRefField('optevia_SectorNatureOfInterest'),
        'employee_range': cdms_fields.IdRefField('optevia_EmployeeRange'),
        'balance_sheet_range': cdms_fields.IdRefField('optevia_BalanceSheetRange'),
        'organisation_size': cdms_fields.IdRefField('optevia_OrganisationSize'),

        'business_type_code': cdms_fields.OptionSetValueField('BusinessTypeCode'),
        'account_classification': cdms_fields.IdRefField('detica_AccountClassification'),
        'account_classification_code': cdms_fields.OptionSetValueField('AccountClassificationCode'),
        'turnover_range': cdms_fields.IdRefField('optevia_TurnoverRange'),
        'telephone_type': cdms_fields.IdRefField('optevia_TelephoneType'),
        'account_category_code': cdms_fields.OptionSetValueField('AccountCategoryCode'),
        'state_code': cdms_fields.OptionSetValueField('StateCode'),
        'customer_type_code': cdms_fields.OptionSetValueField('CustomerTypeCode'),
        'account_rating_code': cdms_fields.OptionSetValueField('AccountRatingCode'),
        'database_source': cdms_fields.IdRefField('optevia_DatabaseSource'),
        'email_address_type': cdms_fields.IdRefField('optevia_EmailAddressType'),
        'transaction_currency_id': cdms_fields.IdRefField('TransactionCurrencyId'),

        'uk_region': cdms_fields.IdRefField('optevia_UKRegion'),
        'business_type': cdms_fields.IdRefField('optevia_BusinessType'),
        'address_type': cdms_fields.IdRefField('optevia_AddressType'),


        'master_cdms_pk': cdms_fields.IdRefField('MasterId'),
        'parent_cdms_pk': cdms_fields.IdRefField('ParentAccountId'),
        'preferred_equipment_id': cdms_fields.IdRefField('PreferredEquipmentId'),
        'territory_id': cdms_fields.IdRefField('TerritoryId'),
        'preferred_service_id': cdms_fields.IdRefField('PreferredServiceId'),
        'default_price_level_id': cdms_fields.IdRefField('DefaultPriceLevelId'),
        'preferred_system_user_id': cdms_fields.IdRefField('PreferredSystemUserId'),
        'owning_team': cdms_fields.IdRefField('OwningTeam'),
        'originating_lead_id': cdms_fields.IdRefField('OriginatingLeadId'),

        'primary_contact_cdms_pk': cdms_fields.IdRefField('PrimaryContactId'),
        'owner_id': cdms_fields.IdRefField('OwnerId'),

        'owning_user': cdms_fields.IdRefField('OwningUser'),
        'created_on_behalf_by': cdms_fields.IdRefField('CreatedOnBehalfBy'),
        'created_by': cdms_fields.IdRefField('CreatedBy'),
        'modified_by': cdms_fields.IdRefField('ModifiedBy'),
        'modified_on_behalf_by': cdms_fields.IdRefField('ModifiedOnBehalfBy'),

    }
    service = 'Account'

    # def update_cdms_data_from_local(self, local_obj, cdms_data):
    #     """
    #     Add PAFOverride value to cdms_data.
    #     """
    #     cdms_data = super(OrganisationMigrator, self).update_cdms_data_from_local(
    #         local_obj, cdms_data
    #     )
    #
    #     if cdms_data:
    #         cdms_data['optevia_PAFOverride'] = True
    #     return cdms_data


class ContactMigrator(BaseCDMSMigrator):
    fields = {
        'first_name': cdms_fields.StringField('FirstName'),
        'last_name': cdms_fields.StringField('LastName'),
        'organisation': cdms_fields.ForeignKeyField(
            'ParentCustomerId',
            fk_model='organisation.Organisation'
        )
    }
    service = 'Contact'
